import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import Button from '@mui/material/Button';
import styled from '@emotion/styled'
import theme from '../src/theme'
import Box from '@mui/material/Box'

const Title = styled.h1`
    text-align: center;
    margin: 0;
    padding: 5rem 0;
    lineHeight: 1.15;
    font-size: 4rem;
`;

const MenuContainer = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
    max-width: 800px;
    margin-top: 3rem;
`;

const Menu = styled.div`
    margin: 1rem;
    padding: 1.5rem;
    text-align: center;
    text-decoration: none;
    transition: color 0.15s ease, border-color 0.15s ease;
    width: 35%;
`;

const Footer = styled.div`
    position: fixed;
    bottom: 0;
    padding: 30px;
    text-align: center;
    background: ${theme.palette.primary.light};
    width: 100vw
`;

export default function Home() {

  return (
    <React.Fragment>
      <Box sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <Head>
          <title>Apple vs. Pineapple</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <Title>
            Welcome to Index Page!
          </Title>

          <MenuContainer>
            <Menu>
              <Button variant="outlined" sx={{ minWidth: 200 }}>
                <Link href="/1">
                  <a>
                    apple
                  </a>
                </Link>
              </Button>
            </Menu>
            <Menu>
              <Button variant="outlined" sx={{ minWidth: 200 }}>
                <Link href="/11">
                  <a>
                    pineapple
                  </a>
                </Link>
              </Button>
            </Menu>
          </MenuContainer>
        </main>

        <Footer>
          choulc@github
        </Footer>
      </Box>
    </React.Fragment>
  )
}
