import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import Button from '@mui/material/Button';
import styled from '@emotion/styled'
import theme from '../src/theme'
import Box from '@mui/material/Box'
import listData from '../data/fruitListData.json'

const Title = styled.h1`
    text-align: center;
    margin: 0;
    padding: 2.5rem 0;
    lineHeight: 1.15;
    font-size: 2rem;
    @media (min-width: 600px){
      font-size: 4rem;
      padding: 5rem 0;
    }
`;

const MenuContainer = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
    max-width: 800px;
    margin-top: 1rem;
    padding-bottom:20px;
    @media (min-width: 600px){
      padding-bottom: 80px;
    }
`;

const Menu = styled.div`
    margin: 0.5rem;
    padding: 1rem;
    text-align: center;
    text-decoration: none;
    transition: color 0.15s ease, border-color 0.15s ease;
    width: 35%;
`;

const Footer = styled.div`
    position: fixed;
    bottom: 0;
    padding: 30px;
    text-align: center;
    background: ${theme.palette.primary.light};
    width: 100vw
`;

export default function Home(props) {

  const { list } = props

  return (
    <React.Fragment>
      <Box sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}>
        <Head>
          <title>Apple vs. Pineapple</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <Title>
            Welcome to Index Page!
          </Title>

          <MenuContainer>
            {list["apple"].map(apple => (
              <Menu key={apple.id}>
                <Button variant="outlined" sx={{ minWidth: '14ch' }} color="secondary">
                  <Link href={`/${apple.id}`}>
                    <a>
                      {apple.name}
                    </a>
                  </Link>
                </Button>
              </Menu>
            ))}
            {list["pineapple"].map(pineapple => (
              <Menu key={pineapple.id}>
                <Button variant="outlined" sx={{ minWidth: '14ch' }}>
                  <Link href={`/${pineapple.id}`}>
                    <a>
                      {pineapple.name}
                    </a>
                  </Link>
                </Button>
              </Menu>
            ))}
          </MenuContainer>
        </main>

        <Footer>
          choulc@github
        </Footer>
      </Box>
    </React.Fragment>
  )
}

export async function getStaticProps() {

  return {
    props: {
      list: listData
    }
  }
}
